"""
Ad-hoc Script: Reset Portfolio Manager Data for Testing

This script resets performance-related data generated by portfolio manager runs
while preserving the core portfolio and stock holdings. Useful for testing
portfolio manager multiple times per day.

Usage:
    python scripts/reset_manager_data.py
    python scripts/reset_manager_data.py --profile aggressive
    python scripts/reset_manager_data.py --confirm  # Skip confirmation prompt
"""

import sys
from pathlib import Path
from datetime import datetime, date, timedelta
import argparse

sys.path.insert(0, str(Path(__file__).parent.parent))

from utils.logger import get_logger
from utils.db_service import get_db_service

logger = get_logger("scripts.reset_manager_data")


def reset_manager_data(profile: str = None, keep_days: int = 0, confirm: bool = False):
    """
    Reset portfolio manager data for testing

    Args:
        profile: Portfolio profile to reset (None = all portfolios)
        keep_days: Keep data from last N days (0 = delete all)
        confirm: Skip confirmation prompt if True
    """
    db = get_db_service()

    # Get portfolio IDs to reset
    if profile:
        portfolio = db.get_active_portfolio(profile)
        if not portfolio:
            logger.error(f"No active portfolio found for profile: {profile}")
            return False
        portfolio_ids = [portfolio['id']]
        scope = f"{profile} portfolio"
    else:
        portfolios = db.get_all_portfolios()
        portfolio_ids = [p['id'] for p in portfolios]
        scope = "all portfolios"

    if not portfolio_ids:
        logger.error("No portfolios found to reset")
        return False

    logger.info(f"Preparing to reset data for {scope}")
    logger.info(f"Portfolio IDs: {portfolio_ids}")

    # Calculate cutoff date
    cutoff_date = None
    if keep_days > 0:
        cutoff_date = date.today() - timedelta(days=keep_days)
        logger.info(f"Will keep data from {cutoff_date} onwards (last {keep_days} days)")
    else:
        logger.info("Will delete all manager-generated data")

    # Show what will be deleted
    print("\n" + "="*80)
    print("DATA RESET PREVIEW")
    print("="*80)
    print(f"Scope: {scope}")
    print(f"Portfolio IDs: {', '.join(map(str, portfolio_ids))}")
    print(f"Keep recent data: {'Yes, last ' + str(keep_days) + ' days' if keep_days > 0 else 'No, delete all'}")
    print("\nThe following data will be DELETED:")
    print("  - Manager updates (recommendations, analysis)")
    print("  - Rebalancing recommendations")
    print("  - Performance metrics (daily returns, portfolio values)")
    print("  - Portfolio snapshots")
    print("  - Benchmark comparisons")
    print("  - Daily price data")
    print("  - Index price data")
    print("  - Market events")
    print("  - Transaction history (BUY/SELL records)")
    print("\nThe following data will be PRESERVED:")
    print("  - Portfolio configuration")
    print("  - Stock holdings (allocation, entry price, targets)")
    print("  - Investment views (rationale, triggers)")
    print("  - Key metrics snapshots")
    print("="*80)

    # Confirmation
    if not confirm:
        response = input("\nProceed with data reset? (yes/no): ").strip().lower()
        if response not in ['yes', 'y']:
            logger.info("Reset cancelled by user")
            return False

    print("\nResetting data...")

    try:
        # Build WHERE clauses
        portfolio_filter = f"portfolio_id IN ({','.join(map(str, portfolio_ids))})"
        date_filter = ""
        if cutoff_date:
            date_filter = f" AND created_at < '{cutoff_date}'"

        # Reset manager updates
        logger.info("Deleting manager updates...")
        sql = f"DELETE FROM manager_updates WHERE {portfolio_filter}{date_filter}"
        affected = db.execute_update(sql)
        logger.info(f"  Deleted {affected} manager updates")

        # Reset rebalancing recommendations
        logger.info("Deleting rebalancing recommendations...")
        sql = f"DELETE FROM rebalancing_recommendations WHERE {portfolio_filter}{date_filter}"
        affected = db.execute_update(sql)
        logger.info(f"  Deleted {affected} rebalancing recommendations")

        # Reset performance metrics
        logger.info("Deleting performance metrics...")
        sql = f"DELETE FROM performance_metrics WHERE {portfolio_filter}{date_filter}"
        affected = db.execute_update(sql)
        logger.info(f"  Deleted {affected} performance metrics")

        # Reset portfolio snapshots
        logger.info("Deleting portfolio snapshots...")
        sql = f"DELETE FROM portfolio_snapshots WHERE {portfolio_filter}{date_filter}"
        affected = db.execute_update(sql)
        logger.info(f"  Deleted {affected} portfolio snapshots")

        # Reset benchmark comparisons
        logger.info("Deleting benchmark comparisons...")
        sql = f"DELETE FROM benchmark_comparison WHERE {portfolio_filter}{date_filter}"
        affected = db.execute_update(sql)
        logger.info(f"  Deleted {affected} benchmark comparisons")

        # Reset market events
        logger.info("Deleting market events...")
        sql = f"DELETE FROM market_events WHERE {portfolio_filter}{date_filter}"
        affected = db.execute_update(sql)
        logger.info(f"  Deleted {affected} market events")

        # Reset transactions
        logger.info("Deleting transactions...")
        sql = f"DELETE FROM transactions WHERE {portfolio_filter}{date_filter}"
        affected = db.execute_update(sql)
        logger.info(f"  Deleted {affected} transactions")

        # Reset daily prices (only for stocks in these portfolios)
        logger.info("Deleting daily prices...")
        stock_ids_query = f"SELECT id FROM stocks WHERE {portfolio_filter}"
        sql = f"""
            DELETE FROM daily_prices
            WHERE stock_id IN ({stock_ids_query})
            {f"AND created_at < '{cutoff_date}'" if cutoff_date else ''}
        """
        affected = db.execute_update(sql)
        logger.info(f"  Deleted {affected} daily price records")

        # Reset index prices (keep if keep_days > 0, delete all otherwise)
        if keep_days == 0:
            logger.info("Deleting index prices...")
            sql = "DELETE FROM index_prices"
            affected = db.execute_update(sql)
            logger.info(f"  Deleted {affected} index price records")
        else:
            logger.info("Deleting old index prices...")
            sql = f"DELETE FROM index_prices WHERE price_date < '{cutoff_date}'"
            affected = db.execute_update(sql)
            logger.info(f"  Deleted {affected} old index price records")

        # Reset rebalancing history
        logger.info("Deleting rebalancing history...")
        sql = f"DELETE FROM rebalancing_history WHERE {portfolio_filter}{date_filter}"
        affected = db.execute_update(sql)
        logger.info(f"  Deleted {affected} rebalancing history records")

        print("\n" + "="*80)
        print("DATA RESET COMPLETE")
        print("="*80)
        print(f"Portfolio manager data has been reset for {scope}")
        print("You can now run the portfolio manager for fresh testing")
        print("="*80)

        return True

    except Exception as e:
        logger.error(f"Error during reset: {e}", exc_info=True)
        print(f"\nERROR: Failed to reset data: {e}")
        return False


def main():
    """Main entry point"""
    parser = argparse.ArgumentParser(
        description="Reset portfolio manager data for testing",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        '--profile',
        type=str,
        choices=['aggressive', 'moderate', 'defensive'],
        help='Portfolio profile to reset (default: all portfolios)'
    )
    parser.add_argument(
        '--keep-days',
        type=int,
        default=0,
        help='Keep data from last N days (default: 0 = delete all)'
    )
    parser.add_argument(
        '--confirm',
        action='store_true',
        help='Skip confirmation prompt'
    )

    args = parser.parse_args()

    # Run reset
    success = reset_manager_data(
        profile=args.profile,
        keep_days=args.keep_days,
        confirm=args.confirm
    )

    sys.exit(0 if success else 1)


if __name__ == '__main__':
    main()
